name: flappy_translator
description: A Flutter internationalized strings generator.
version: 1.0.4
author: Equinoa<register@smartnsoft.com>
homepage: https://github.com/smartnsoft/FlappyTranslator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.0.3
  yaml: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
